---
- name: installing apache2
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copy Template
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: "root"
    group: "root"
    mode: 0777
  with_items:
   - { name: "{{ansible_hostname}}", internal: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}", external: "{{hostvars[inventory_hostname].inventory_hostname}}"}
