---
  - name: Configure apache server
    hosts: all   
    vars:
        ansible_user: mmalyarova
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    become: yes
    become_method: sudo
    gather_facts: yes
    roles:
        - web